/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-container": "#ffd1ae",
        "surface-container-high": "#e2e7ff",
        "surface-container-lowest": "#ffffff",
        "tertiary-container": "#914d00",
        "inverse-primary": "#95d4b3",
        "on-tertiary-fixed-variant": "#6e3900",
        "on-error": "#ffffff",
        "secondary": "#006c48",
        "surface-bright": "#faf8ff",
        "secondary-container": "#92f7c3",
        "on-primary-fixed-variant": "#0e5138",
        "primary-container": "#2d6a4f",
        "surface-variant": "#dae2fd",
        "error-container": "#ffdad6",
        "tertiary-fixed-dim": "#ffb77d",
        "on-surface-variant": "#404943",
        "on-tertiary-fixed": "#2f1500",
        "on-error-container": "#93000a",
        "surface-container-highest": "#dae2fd",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#75daa8",
        "surface-container": "#eaedff",
        "tertiary": "#6f3a00",
        "outline": "#707973",
        "surface": "#faf8ff",
        "surface-tint": "#2c694e",
        "on-surface": "#131b2e",
        "secondary-fixed": "#92f7c3",
        "error": "#ba1a1a",
        "primary-fixed-dim": "#95d4b3",
        "primary": "#0f5238",
        "on-background": "#131b2e",
        "tertiary-fixed": "#ffdcc3",
        "outline-variant": "#bfc9c1",
        "inverse-surface": "#283044",
        "on-secondary-container": "#00734d",
        "inverse-on-surface": "#eef0ff",
        "on-secondary-fixed": "#002113",
        "on-secondary": "#ffffff",
        "surface-dim": "#d2d9f4",
        "on-primary-container": "#a8e7c5",
        "background": "#faf8ff",
        "surface-container-low": "#f2f3ff",
        "on-secondary-fixed-variant": "#005235",
        "on-primary-fixed": "#002114",
        "primary-fixed": "#b1f0ce",
        "on-tertiary": "#ffffff",
        forestSage: '#2D6A4F',
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "16px",
        "margin-desktop": "40px",
        gutter: "24px",
        "container-max": "1280px",
        base: "8px",
      },
      fontFamily: {
        "display-lg": ["Outfit", "sans-serif"],
        "headline-lg": ["Outfit", "sans-serif"],
        "headline-md": ["Outfit", "sans-serif"],
        "label-sm": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg-mobile": ["Outfit", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
      },
      maxWidth: {
        "container-max": "1280px",
      },
    },
  },
  plugins: [],
}